# Generated by Django 5.2.12 on 2026-10-09 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('client', 'Ustachi (mijoz)'), ('master', 'Ustachi Pro (usta)')], max_length=16, verbose_name='Ilova')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=16, verbose_name='Platforma')),
                ('latest_version', models.CharField(help_text="Do'konda turgan eng yangi versiya, masalan 1.2.3.", max_length=20, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+){0,3}$', "Versiya faqat raqam va nuqtadan iborat bo'lsin: 1.2.3")], verbose_name='Oxirgi versiya')),
                ('min_version', models.CharField(blank=True, default='', help_text="Bundan PAST versiyalarda oyna yopilmaydi — ilovadan foydalanib bo'lmaydi. Bo'sh qoldirilsa majburiy yangilash ishlamaydi.", max_length=20, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+){0,3}$', "Versiya faqat raqam va nuqtadan iborat bo'lsin: 1.2.3")], verbose_name='Eng past ruxsat etilgan versiya')),
                ('store_url', models.URLField(blank=True, default='', help_text="«Yangilash» tugmasi shu manzilni ochadi: Play Market, App Store yoki to'g'ridan-to'g'ri APK.", max_length=500, verbose_name='Yangilash havolasi')),
                ('notes', models.TextField(blank=True, default='', help_text="Har bir yangilik — ALOHIDA QATOR. Bo'sh qoldirsangiz ilova umumiy matn ko'rsatadi, oyna baribir to'g'ri ishlaydi.", verbose_name='Nima yangilandi')),
                ('is_active', models.BooleanField(default=False, help_text="O'chirilsa hech kimga yangilanish oynasi chiqmaydi.", verbose_name='Yoqilgan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ilova versiyasi',
                'verbose_name_plural': 'Ilova versiyalari',
                'ordering': ['app', 'platform'],
                'constraints': [models.UniqueConstraint(fields=('app', 'platform'), name='uniq_app_release_per_platform')],
            },
        ),
    ]
