# Generated by Django 5.2.12 on 2026-10-09 07:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('code', models.SlugField(blank=True, max_length=40, null=True, unique=True, verbose_name='Kod')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name="O'lchov birligi")),
                ('unit_question', models.CharField(blank=True, default='', max_length=140, verbose_name='Narx savoli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('calculator', models.CharField(blank=True, choices=[('', "Yo'q — narx chatda kelishiladi"), ('rom', "Rom (chizma ekrani: shakl va o'lcham)"), ('area', "Maydon (m² bo'yicha pog'onali narx)"), ('variant', "Variant (Odatiy/Standart/Premium — har biri o'z m² narxida)"), ('masonry', "G'isht terish (devor o'lchami → g'isht soni va narxi)"), ('roof', "Tom yopish (uy o'lchami → tom maydoni va material narxi)"), ('beton', "Poydevor (uy o'lchami → beton kubi va armatura)"), ('electrical', 'Elektr montaj (materiallar hisobi)'), ('heating', 'Uyni isitish (xonalar → radiator, truba, kotyol)')], default='', max_length=16, verbose_name='Narx kalkulyatori')),
                ('variant_price_is_material', models.BooleanField(default=False, help_text="Belgilansa: ko'rsatilgan narx faqat material. Usta har variantga o'z m² stavkasini kiritadi va mijoz javob kelganda jamini ko'radi.", verbose_name='Variant narxi — material tannarxi')),
                ('group', models.CharField(blank=True, default='', max_length=30, verbose_name='Guruh')),
                ('unit_by_master', models.BooleanField(default=False, help_text="Belgilansa: har usta o'zi birlik tanlaydi (soat, reys, km...) va narxini yozadi.", verbose_name='Birlikni usta tanlaydi')),
                ('note_by_master', models.BooleanField(default=False, help_text="Belgilansa: ustadan narx so'ralmaydi, u o'z xizmati va narxlarini erkin matnda yozadi.", verbose_name="Narx o'rniga usta izohi")),
                ('has_repair', models.BooleanField(default=False, help_text="Belgilansa: mijoz soha ichida «Yangi ish / Ta'mir» tanlovini ko'radi. Ta'mirda narx hisoblanmaydi — usta ko'rib aytadi.", verbose_name="Ta'mir bor")),
            ],
            options={
                'verbose_name': "Usta yo'nalishi",
                'verbose_name_plural': "Usta yo'nalishlari",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('auth', "Kirish / ro'yxatdan o'tish"), ('delete_account', "Akkauntni o'chirish")], default='auth', max_length=20, verbose_name='Maqsad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Telefon OTP',
                'verbose_name_plural': 'Telefon OTPlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAuthFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('chat_id', models.BigIntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('step', models.CharField(default='phone', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('grants_master', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_auth_user_id', models.BigIntegerField(blank=True, help_text='Mijoz Telegram autentifikatsiyasi uchun biriktirilgan Telegram user ID.', null=True, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Manzil')),
                ('is_master', models.BooleanField(default=False, help_text='Usta (master) roli. Mijozlik roli hammada bor.', verbose_name='Usta')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='locations.city', verbose_name='Tuman/shahar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='locations.region', verbose_name='Viloyat')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='FCM token')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=16, verbose_name='Platforma')),
                ('device_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Qurilma')),
                ('app', models.CharField(blank=True, choices=[('client', 'Mijoz ilovasi'), ('master', 'Usta ilovasi')], default='', max_length=8, verbose_name='Ilova')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oxirgi faollik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Qurilma tokeni',
                'verbose_name_plural': 'Qurilma tokenlari',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveSmallIntegerField(verbose_name='Tajriba (yil)')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Qisqacha izoh')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('accepts_orders', models.BooleanField(default=True, help_text="O'chirilsa yangi e'lon haqida push kelmaydi (ro'yxatda ko'rinadi).", verbose_name='Buyurtma qabul qiladi')),
                ('does_plastic', models.BooleanField(default=True, verbose_name='Plastik ishlayman')),
                ('does_aluminium', models.BooleanField(default=True, verbose_name='Alyuminiy ishlayman')),
                ('does_termo', models.BooleanField(default=True, verbose_name='Termo ishlayman')),
                ('does_repairs', models.BooleanField(default=False, help_text="Yoqilsa ta'mir e'lonlari ham ko'rinadi (eski rom/eshikni sozlash, furnitura, oyna almashtirish).", verbose_name="Ta'mirga chiqaman")),
                ('company_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Korxona nomi')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='masters/company/', verbose_name='Korxona logotipi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('specialties', models.ManyToManyField(blank=True, related_name='masters', to='accounts.masterspecialty', verbose_name="Yo'nalishlar")),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='accounts.masterspecialty', verbose_name="Asosiy yo'nalish")),
            ],
            options={
                'verbose_name': 'Usta profili',
                'verbose_name_plural': 'Usta profillari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterSpecialtyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Izoh')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_notes', to='accounts.masterprofile', verbose_name='Usta profili')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_notes', to='accounts.masterspecialty', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Usta izohi',
                'verbose_name_plural': 'Usta izohlari',
                'ordering': ['specialty__order'],
            },
        ),
        migrations.CreateModel(
            name='MasterWorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='masters/work_samples/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_samples', to='accounts.masterprofile', verbose_name='Usta profili')),
            ],
            options={
                'verbose_name': 'Ish namunasi',
                'verbose_name_plural': 'Ish namunalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyAreaTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_to_area', models.DecimalField(blank=True, decimal_places=2, help_text="Shu son ham kiradi. Bo'sh qoldirilsa — cheksiz (eng katta maydonlar uchun oxirgi pog'ona).", max_digits=10, null=True, verbose_name='Shu maydongacha (m²)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="1 m² narxi (so'm)")),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_tiers', to='accounts.masterspecialty', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Maydon narxi',
                'verbose_name_plural': 'Maydon narxlari',
                'ordering': [models.OrderBy(models.F('up_to_area'), nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyRepairProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, verbose_name='Kod')),
                ('title', models.CharField(max_length=80, verbose_name='Nomi')),
                ('hint', models.CharField(blank=True, default='', max_length=140, verbose_name='Izoh')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_problems', to='accounts.masterspecialty', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': "Ta'mir muammosi",
                'verbose_name_plural': "Ta'mir muammolari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
                ('size', models.CharField(blank=True, default='', help_text="Masalan «40×40 sm». Bo'sh qoldirilsa ko'rsatilmaydi.", max_length=40, verbose_name="O'lchami")),
                ('note', models.CharField(blank=True, default='', help_text="Mijozga ko'rinadigan bir qatorlik farq: «1 qanotli laminatsiya».", max_length=140, verbose_name='Izoh')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="1 m² narxi (so'm)")),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='accounts.masterspecialty', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyBrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pishgan', "Pishgan g'isht"), ('xom', "Xom g'isht"), ('penoblok', 'Penoblok'), ('shlakoblok', 'Shlakoblok')], default='pishgan', max_length=20, verbose_name='Material')),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
                ('length_mm', models.PositiveSmallIntegerField(default=250, verbose_name='Uzunligi (mm)')),
                ('width_mm', models.PositiveSmallIntegerField(default=125, verbose_name='Eni (mm)')),
                ('height_mm', models.PositiveSmallIntegerField(default=88, help_text='Terimdagi bir qator balandligi.', verbose_name="Bo'yi (mm)")),
                ('joint_mm', models.PositiveSmallIntegerField(default=10, help_text="G'ishtlar orasidagi qorishma qalinligi.", verbose_name='Chok (mm)')),
                ('bricks_per_m2_half', models.DecimalField(blank=True, decimal_places=2, help_text="Amaliyotdagi son, chok bilan. Bir g'isht — 2 barobar, bir yarim — 3 barobar. Bo'sh qolsa o'lchamlardan hisoblanadi.", max_digits=7, null=True, verbose_name="1 m² ga, yarim g'ishtda (dona)")),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="1 dona narxi (so'm)")),
                ('mortar_per_brick', models.DecimalField(decimal_places=2, default=0, help_text="Qum, ohak, sement narxi ÷ shu qorishmaga teriladigan g'isht soni. Singan g'ishtga qo'shilmaydi.", max_digits=10, verbose_name="Qorishma, 1 dona terimga (so'm)")),
                ('waste_pct', models.DecimalField(decimal_places=2, default=Decimal('1.8'), max_digits=5, verbose_name="Singan g'isht zaxirasi (%)")),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bricks', to='accounts.masterspecialty', verbose_name="Yo'nalish")),
                ('variant', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brick', to='accounts.specialtyvariant', verbose_name='Usta narxi uchun tur')),
            ],
            options={
                'verbose_name': "G'isht turi",
                'verbose_name_plural': "G'isht turlari",
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='MasterSpecialtyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(verbose_name="Narx (so'm)")),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='Birlik (usta tanlagan)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='accounts.masterprofile', verbose_name='Usta profili')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='accounts.masterspecialty', verbose_name="Yo'nalish")),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_rates', to='accounts.specialtyvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Usta narxi',
                'verbose_name_plural': 'Usta narxlari',
                'ordering': ['specialty__order'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAuthGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('is_new_user', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__isnull', False)), fields=('phone_number',), name='accounts_user_phone_number_not_null_unique'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='accounts_de_user_id_d068f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='masterspecialtynote',
            constraint=models.UniqueConstraint(fields=('profile', 'specialty'), name='uniq_master_specialty_note'),
        ),
        migrations.AddConstraint(
            model_name='specialtyareatier',
            constraint=models.UniqueConstraint(fields=('specialty', 'up_to_area'), name='uniq_specialty_area_tier'),
        ),
        migrations.AddConstraint(
            model_name='specialtyareatier',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='area_tier_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='specialtyrepairproblem',
            constraint=models.UniqueConstraint(fields=('specialty', 'code'), name='unique_repair_problem_code'),
        ),
        migrations.AddConstraint(
            model_name='specialtyvariant',
            constraint=models.UniqueConstraint(fields=('specialty', 'name'), name='uniq_specialty_variant_name'),
        ),
        migrations.AddConstraint(
            model_name='specialtyvariant',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='variant_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='specialtybrick',
            constraint=models.UniqueConstraint(fields=('specialty', 'name'), name='uniq_specialty_brick_name'),
        ),
        migrations.AddConstraint(
            model_name='specialtybrick',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0), ('waste_pct__gte', 0)), name='brick_prices_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='masterspecialtyrate',
            constraint=models.UniqueConstraint(fields=('profile', 'specialty', 'variant'), name='uniq_master_rate_variant'),
        ),
        migrations.AddConstraint(
            model_name='masterspecialtyrate',
            constraint=models.UniqueConstraint(condition=models.Q(('unit', ''), ('variant__isnull', True)), fields=('profile', 'specialty'), name='uniq_master_rate'),
        ),
        migrations.AddConstraint(
            model_name='masterspecialtyrate',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True), models.Q(('unit', ''), _negated=True)), fields=('profile', 'specialty', 'unit'), name='uniq_master_rate_unit'),
        ),
    ]
