# Generated by Django 5.2.12 on 2026-10-09 08:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_specialty_catalog'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sync_client_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Qurilma ID')),
                ('customer_name', models.CharField(max_length=120, verbose_name='Buyurtmachi')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Telefon')),
                ('customer_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Manzil')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('note', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('done', 'Yakunlangan'), ('debt', 'Qarzdor'), ('cancelled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Holat')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlandi')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_orders', to=settings.AUTH_USER_MODEL, verbose_name='Usta')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usta buyurtmasi',
                'verbose_name_plural': 'Usta buyurtmalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Nomi')),
                ('material_label', models.CharField(blank=True, default='', max_length=60, verbose_name='Material')),
                ('width_mm', models.PositiveIntegerField(default=0, verbose_name='Eni (mm)')),
                ('height_mm', models.PositiveIntegerField(default=0, verbose_name='Balandligi (mm)')),
                ('qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sanoq')),
                ('drawing', models.JSONField(blank=True, default=dict, verbose_name='Chizma')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.masterorder', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, default='', verbose_name='Shartlar')),
                ('proposal', models.JSONField(blank=True, default=dict, verbose_name='Taklif')),
                ('calculated_price', models.BigIntegerField(default=0, verbose_name="Mijoz hisobi (so'm)")),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Manzil')),
                ('is_public', models.BooleanField(default=True, verbose_name='Hammaga ochiq')),
                ('is_repair', models.BooleanField(default=False, verbose_name="Ta'mir")),
                ('status', models.CharField(choices=[('published', "E'lon qilingan"), ('assigned', 'Usta tanlangan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan'), ('expired', "Muddati o'tgan")], default='published', max_length=20, verbose_name='Holat')),
                ('stage', models.CharField(blank=True, choices=[('accepted', 'Qabul qilindi'), ('measured', "O'lchov olindi"), ('production', 'Ishlab chiqarish'), ('installation', "O'rnatish"), ('handover', 'Topshirildi')], max_length=20, null=True, verbose_name='Bosqich')),
                ('expires_at', models.DateTimeField(verbose_name="E'lon muddati")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlandi')),
                ('telegram_message_id', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('telegram_post_is_photo', models.BooleanField(default=False, editable=False)),
                ('cancelled_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Bekor qilish sababi')),
                ('assigned_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Tanlangan usta')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='locations.city', verbose_name='Tuman/shahar')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='locations.region', verbose_name='Viloyat')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.masterspecialty', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_published', 'Yangi buyurtma'), ('order_invite', 'Sizga taklif'), ('order_invite_declined', 'Usta taklifni rad etdi'), ('order_response', 'Usta javob berdi'), ('order_chosen', 'Usta tanlandi'), ('order_not_chosen', 'Boshqa usta tanlandi'), ('order_stage', "Bosqich o'zgardi"), ('order_completed', 'Buyurtma yakunlandi'), ('order_cancelled', 'Buyurtma bekor qilindi'), ('review_received', 'Yangi baho'), ('chat_message', 'Yangi xabar')], max_length=32, verbose_name='Turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('body', models.CharField(blank=True, default='', max_length=500, verbose_name='Matn')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('app', models.CharField(blank=True, choices=[('client', 'Mijoz ilovasi'), ('master', 'Usta ilovasi')], default='', max_length=8, verbose_name='Ilova')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi xabar')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads_as_master', to=settings.AUTH_USER_MODEL, verbose_name='Usta')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Suhbat',
                'verbose_name_plural': 'Suhbatlar',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Javob kutilmoqda'), ('accepted', 'Usta qabul qildi'), ('declined', 'Usta rad etdi')], default='pending', max_length=20, verbose_name='Holat')),
                ('decline_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Rad etish sababi')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_invites', to=settings.AUTH_USER_MODEL, verbose_name='Usta')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Ustaga taklif',
                'verbose_name_plural': 'Ustaga takliflar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('interested', 'Qabul qilaman'), ('withdrawn', 'Voz kechdi'), ('chosen', 'Tanlandi'), ('rejected', 'Tanlanmadi')], default='interested', max_length=20, verbose_name='Holat')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_responses', to=settings.AUTH_USER_MODEL, verbose_name='Usta')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Usta javobi',
                'verbose_name_plural': 'Usta javoblari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('accepted', 'Qabul qilindi'), ('measured', "O'lchov olindi"), ('production', 'Ishlab chiqarish'), ('installation', "O'rnatish"), ('handover', 'Topshirildi')], max_length=20, verbose_name='Bosqich')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kim')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Bosqich hodisasi',
                'verbose_name_plural': 'Bosqich hodisalari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baho (1-5)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usta')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Matn')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.chatthread', verbose_name='Suhbat')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread', '-created_at'], name='orders_chat_thread__1c5afc_idx'), models.Index(fields=['thread', 'is_read', '-created_at'], name='orders_chat_thread__028f11_idx'), models.Index(fields=['thread', '-id'], name='orders_chat_thread__3315d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExclusiveTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_territories', to='locations.city', verbose_name='Tuman/shahar')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_territories', to=settings.AUTH_USER_MODEL, verbose_name='Usta')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_territories', to='accounts.masterspecialty', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Biriktirilgan hudud',
                'verbose_name_plural': 'Biriktirilgan hududlar',
                'constraints': [models.UniqueConstraint(fields=('specialty', 'district'), name='unique_territory_specialty_district')],
            },
        ),
        migrations.AddIndex(
            model_name='masterorder',
            index=models.Index(fields=['master', '-created_at'], name='orders_mast_master__86c5e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='masterorder',
            constraint=models.UniqueConstraint(condition=models.Q(('sync_client_id', ''), _negated=True), fields=('master', 'sync_client_id'), name='uniq_master_order_sync_client_id'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'region'], name='orders_orde_status_2a83f4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', '-created_at'], name='orders_orde_client__16ef1b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'specialty', 'region'], name='orders_orde_status_16bd44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='orders_noti_user_id_7dc029_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(fields=('order', 'master'), name='orders_chatthread_unique'),
        ),
        migrations.AddIndex(
            model_name='orderinvite',
            index=models.Index(fields=['master', 'status'], name='orders_orde_master__22fe5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderinvite',
            constraint=models.UniqueConstraint(fields=('order', 'master'), name='orders_invite_unique_master'),
        ),
        migrations.AddConstraint(
            model_name='orderresponse',
            constraint=models.UniqueConstraint(fields=('order', 'master'), name='orders_response_unique_master'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['master', '-created_at'], name='orders_revi_master__7d5b5d_idx'),
        ),
    ]
